---
title: "tidy_tuesday_09_01_Julia_Silge"
author: "JK"
date: "9/6/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)

key_crop_yields <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-09-01/key_crop_yields.csv")
land_use <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-09-01/land_use_vs_yield_change_in_cereal_production.csv")
```

```{r}
top_contries <- land_use %>%
  janitor::clean_names() %>%
  filter(!is.na(code), entity != "World") %>%
  group_by(entity) %>%
  filter(year == max(year)) %>%
  ungroup() %>%
  slice_max(total_population_gapminder, n = 30) %>%
  pull(entity)

yield_tidy <- key_crop_yields %>%
  janitor::clean_names() %>%
  rename_with(~ gsub("_tonnes_per_hectare", "", .x)) %>%
  pivot_longer(wheat:bananas,
               names_to = "crop",
               values_to = "yield") %>%
  filter(crop %in% c("wheat", "rice", "maize", "barley"),
         entity %in% top_contries,
         !is.na(yield)) 
```

```{r}
library(tidymodels)

tidy_lm <- yield_tidy %>%
  nest(yields = c(year, yield)) %>%
  mutate(model = map(yields, ~ lm(yield ~ year, data = .x)))

tidy_lm %>% view()

slopes <- tidy_lm %>%
  mutate(coef = map(model, tidy)) %>%
  unnest(coef) %>%
  filter(term != "(Intercept)") %>%
  mutate(p.value = p.adjust(p.value))
  
slopes %>% names()
```

```{r}
library(ggrepel)

slopes %>%
  ggplot(aes(estimate, p.value, label = entity)) +
  geom_point(aes(color = crop)) +
  geom_vline(
    xintercept = 0, lty = 2,
    size = 1.5, alpha = 0.7, color = "gray50"
  ) +
  scale_y_log10() +
  geom_text_repel(size = 3) +
  facet_wrap(~crop) +
  theme_light()
```